version: 2

models:
  - name: dim_customers
    description: "Dimension table for active customers"
    columns:
      - name: customer_id
        description: "Primary key"
        tests:
          - not_null
          - unique

      - name: email
        description: "Customer email"
        tests:
          - not_null

      - name: city
        description: "City where customer resides"
        version: 2

  - name: dim_products
    description: "Dimension table for  products"
    columns:
      - name: product_id
        description: "Primary key of the product"
        tests:
          - unique
          - not_null

      - name: product_name
        description: "Name of the product"
        tests:
          - not_null

      - name: category
        description: "Product category"
        tests:
          - not_null
                       
      - name: price
        tests:
          - dbt_utils.accepted_range:
              min_value: 0.01
              max_value: 100000


  - name: dim_orders
    description: "Cleaned and filtered orders from stg_orders with valid status."
    columns:
      - name: order_id
        description: "Primary key"
        tests:
          - not_null
          - unique

      - name: customer_id
        description: "Reference to customer"
        tests:
          - not_null

      - name: product_id
        description: "Reference to product"
        tests:
          - not_null

      - name: status
        description: "Must be one of valid statuses"
        tests:
          - accepted_values:
              values: ['completed', 'shipped', 'delivered']   
              
  - name: fact_orders
    description: "Fact table for all orders and revenue"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - not_null

      - name: product_id
        tests:
          - not_null

      - name: total_revenue
        description: "Quantity x Price"
        
  - name: fact_events
    description: "Fact table capturing event logs with order info and cart metadata."
    columns:
      - name: event_surrogate_id
        tests:
          - not_null
          - unique

      - name: event_id
        tests:
          - not_null
          - unique

      - name: event_time
        description: "Event timestamp (aliased from timestamp)"
        tests:
          - not_null

      - name: event_type
        tests:
          - not_null
          - accepted_values:
              values: ['start_checkout', 'logout']

      - name: customer_id
        tests:
          - not_null

      - name: order_id
        tests: []

      - name: cart_items
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 50

      - name: cart_total
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000

      - name: is_peak
        description: "Flag for peak hour event"